# Generated by Django 6.0.7 on 2026-07-14 15:50

import django.db.models.deletion
import laboratory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('father_surname', models.CharField(max_length=100)),
                ('mother_surname', models.CharField(max_length=100)),
                ('laboratory_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('shift_hours', models.CharField(blank=True, max_length=50, null=True, validators=[laboratory.validators.validate_shift_format])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assistants',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('funding_source', models.CharField(blank=True, max_length=150, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, max_length=12, null=True, validators=[laboratory.validators.validate_positive_budget])),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('father_surname', models.CharField(max_length=100)),
                ('mother_surname', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=150)),
                ('license_number', models.CharField(max_length=50, unique=True, validators=[laboratory.validators.validate_license_length])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scientists',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=100)),
                ('storage_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[laboratory.validators.validate_storage_temperature])),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('projects', models.ForeignKey(db_column='projects_id', on_delete=django.db.models.deletion.CASCADE, to='laboratory.project')),
            ],
            options={
                'db_table': 'samples',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='scientists',
            field=models.ForeignKey(db_column='scientists_id', on_delete=django.db.models.deletion.RESTRICT, to='laboratory.scientist'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True, validators=[laboratory.validators.validate_unsa_email])),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('scientist', 'Scientist'), ('assistant', 'Assistant')], default='assistant', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to='laboratory.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_modified', to='laboratory.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('protocol_description', models.TextField()),
                ('estimated_duration', models.IntegerField(blank=True, null=True, validators=[laboratory.validators.validate_positive_duration])),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_created', to='laboratory.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_modified', to='laboratory.user')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.AddField(
            model_name='scientist',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientists_created', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientists_modified', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='scientist',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.user'),
        ),
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.TextField(blank=True, null=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assistants', models.ForeignKey(blank=True, db_column='assistants_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.assistant')),
                ('samples', models.ForeignKey(db_column='samples_id', on_delete=django.db.models.deletion.CASCADE, to='laboratory.sample')),
                ('scientists', models.ForeignKey(blank=True, db_column='scientists_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.scientist')),
                ('tests', models.ForeignKey(db_column='tests_id', on_delete=django.db.models.deletion.CASCADE, to='laboratory.test')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_created', to='laboratory.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_modified', to='laboratory.user')),
            ],
            options={
                'db_table': 'samples_tests',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_created', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='sample',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_modified', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_modified', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='created_id',
            field=models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants_created', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='modified_id',
            field=models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants_modified', to='laboratory.user'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratory.user'),
        ),
        migrations.CreateModel(
            name='AssistantProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assistants', models.ForeignKey(db_column='assistants_id', on_delete=django.db.models.deletion.CASCADE, to='laboratory.assistant')),
                ('projects', models.ForeignKey(db_column='projects_id', on_delete=django.db.models.deletion.CASCADE, to='laboratory.project')),
                ('created_id', models.ForeignKey(blank=True, db_column='created_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_created', to='laboratory.user')),
                ('modified_id', models.ForeignKey(blank=True, db_column='modified_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_modified', to='laboratory.user')),
            ],
            options={
                'db_table': 'assistants_projects',
                'unique_together': {('assistants', 'projects')},
            },
        ),
    ]
